name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create .env file
        run: |
          touch .env
          echo VITE_API_SERVER_BASE_URL=${{ secrets.VITE_API_SERVER_BASE_URL }} >> .env
          echo VITE_API_STATISTICS_BASE_URL=${{ secrets.VITE_API_STATISTICS_BASE_URL }} >> .env
          cat .env

      - name: npm install
        working-directory: ./
        run: npm install

      - name: npm build
        working-directory: ./
        run: npm run build

      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: "ap-northeast-2"

      - name: deploy to s3
        run: |
          aws s3 sync ./dist s3://www.alioth.site